current:
  namespace: project_dev

server:
  port: 9001

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8845,http://localhost:8847,http://localhost:8849
        namespace: namespace_dev
        group: project_business
    gateway:
      routes:
        - id: ms-zzp-consumer
          uri: http://localhost:8001
          predicates:
            - Path=/**
#https://www.cnblogs.com/hanzeng1993/p/15420383.html